/* tslint:disable */
/* eslint-disable */
/**
 * Star Wars API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Person
 */
export interface Person {
    /**
     * 
     * @type {string}
     * @memberof Person
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Person
     */
    birthYear?: string;
    /**
     * 
     * @type {string}
     * @memberof Person
     */
    eyeColor?: string;
    /**
     * 
     * @type {string}
     * @memberof Person
     */
    gender?: string;
    /**
     * 
     * @type {string}
     * @memberof Person
     */
    hairColor?: string;
    /**
     * 
     * @type {string}
     * @memberof Person
     */
    height?: string;
    /**
     * 
     * @type {string}
     * @memberof Person
     */
    mass?: string;
    /**
     * 
     * @type {string}
     * @memberof Person
     */
    skinColor?: string;
    /**
     * 
     * @type {string}
     * @memberof Person
     */
    homeworld?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof Person
     */
    films?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof Person
     */
    species?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof Person
     */
    starships?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof Person
     */
    vehicles?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof Person
     */
    url?: string;
    /**
     * 
     * @type {string}
     * @memberof Person
     */
    created?: string;
    /**
     * 
     * @type {string}
     * @memberof Person
     */
    edited?: string;
}

export function PersonFromJSON(json: any): Person {
    return PersonFromJSONTyped(json, false);
}

export function PersonFromJSONTyped(json: any, ignoreDiscriminator: boolean): Person {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'birthYear': !exists(json, 'birth_year') ? undefined : json['birth_year'],
        'eyeColor': !exists(json, 'eye_color') ? undefined : json['eye_color'],
        'gender': !exists(json, 'gender') ? undefined : json['gender'],
        'hairColor': !exists(json, 'hair_color') ? undefined : json['hair_color'],
        'height': !exists(json, 'height') ? undefined : json['height'],
        'mass': !exists(json, 'mass') ? undefined : json['mass'],
        'skinColor': !exists(json, 'skin_color') ? undefined : json['skin_color'],
        'homeworld': !exists(json, 'homeworld') ? undefined : json['homeworld'],
        'films': !exists(json, 'films') ? undefined : json['films'],
        'species': !exists(json, 'species') ? undefined : json['species'],
        'starships': !exists(json, 'starships') ? undefined : json['starships'],
        'vehicles': !exists(json, 'vehicles') ? undefined : json['vehicles'],
        'url': !exists(json, 'url') ? undefined : json['url'],
        'created': !exists(json, 'created') ? undefined : json['created'],
        'edited': !exists(json, 'edited') ? undefined : json['edited'],
    };
}

export function PersonToJSON(value?: Person | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'birth_year': value.birthYear,
        'eye_color': value.eyeColor,
        'gender': value.gender,
        'hair_color': value.hairColor,
        'height': value.height,
        'mass': value.mass,
        'skin_color': value.skinColor,
        'homeworld': value.homeworld,
        'films': value.films,
        'species': value.species,
        'starships': value.starships,
        'vehicles': value.vehicles,
        'url': value.url,
        'created': value.created,
        'edited': value.edited,
    };
}


